# TCL File Generated by Component Editor 18.1
# Thu Sep 28 16:48:37 CEST 2023
# DO NOT MODIFY


# 
# cam_arria5 "Content Addressable Memory for Fast Searching (Arria V)" v17.0.2
# Yifeng Wang 2023.09.28.16:48:37
# Output the address, with input of data, which is ideal for searching the data. Functionally inverserd as RAM.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cam_arria5
# 
set_module_property DESCRIPTION "Output the address, with input of data, which is ideal for searching the data. Functionally inverserd as RAM."
set_module_property NAME cam_arria5
set_module_property VERSION 17.0.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Control Plane/Algorithms"
set_module_property AUTHOR "Yifeng Wang"
set_module_property ICON_PATH ../ip_mu3e/drawings/20121123203030!Logo_drawing100.png
set_module_property DISPLAY_NAME "Content Addressable Memory for Fast Searching (Arria V)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cam_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cam_top.vhd VHDL PATH ../ip_mu3e/CAM/cam_top.vhd TOP_LEVEL_FILE
add_fileset_file cam_rtl.vhd VHDL PATH ../ip_mu3e/CAM/cam_rtl.vhd
add_fileset_file cam_erase_ram.vhd VHDL PATH ../ip_mu3e/CAM/cam_erase_ram.vhd
add_fileset_file cam_mem_a5.vhd VHDL PATH ../ip_mu3e/CAM/cam_mem_a5.vhd
add_fileset_file cam_mem_blk_a5.vhd VHDL PATH ../ip_mu3e/CAM/cam_mem_blk_a5.vhd
add_fileset_file addr_enc_logic.vhd VHDL PATH ../ip_mu3e/CAM/addr_enc_logic.vhd
add_fileset_file edge_det.vhd VHDL PATH ../ip_mu3e/CAM/edge_det.vhd
add_fileset_file cam_init_rom.v VERILOG PATH ../ip_mu3e/CAM/cam_init_rom.v
add_fileset_file cam_init.txt OTHER PATH ../ip_mu3e/CAM/cam_init.txt

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL cam_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file debug_cam.spf OTHER PATH output_files/debug_cam.spf


# 
# parameters
# 
add_parameter CAM_SIZE NATURAL 32 "maximum number of elements"
set_parameter_property CAM_SIZE DEFAULT_VALUE 32
set_parameter_property CAM_SIZE DISPLAY_NAME CAM_SIZE
set_parameter_property CAM_SIZE TYPE NATURAL
set_parameter_property CAM_SIZE UNITS None
set_parameter_property CAM_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property CAM_SIZE DESCRIPTION "maximum number of elements"
set_parameter_property CAM_SIZE HDL_PARAMETER true
add_parameter CAM_WIDTH NATURAL 8 "single element bit width"
set_parameter_property CAM_WIDTH DEFAULT_VALUE 8
set_parameter_property CAM_WIDTH DISPLAY_NAME CAM_WIDTH
set_parameter_property CAM_WIDTH TYPE NATURAL
set_parameter_property CAM_WIDTH UNITS None
set_parameter_property CAM_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property CAM_WIDTH DESCRIPTION "single element bit width"
set_parameter_property CAM_WIDTH HDL_PARAMETER true
add_parameter MATCH_MODE STRING Single-Match "Allow multiple identical elements to be matched"
set_parameter_property MATCH_MODE DEFAULT_VALUE Single-Match
set_parameter_property MATCH_MODE DISPLAY_NAME MATCH_MODE
set_parameter_property MATCH_MODE TYPE STRING
set_parameter_property MATCH_MODE ENABLED false
set_parameter_property MATCH_MODE UNITS None
set_parameter_property MATCH_MODE DESCRIPTION "Allow multiple identical elements to be matched"
set_parameter_property MATCH_MODE HDL_PARAMETER true
add_parameter ERASE_SPEED STRING fast "Not Supported"
set_parameter_property ERASE_SPEED DEFAULT_VALUE fast
set_parameter_property ERASE_SPEED DISPLAY_NAME ERASE_SPEED
set_parameter_property ERASE_SPEED TYPE STRING
set_parameter_property ERASE_SPEED ENABLED false
set_parameter_property ERASE_SPEED UNITS None
set_parameter_property ERASE_SPEED DESCRIPTION "Not Supported"
set_parameter_property ERASE_SPEED HDL_PARAMETER true
add_parameter OCCUPANCY_CHECK BOOLEAN true "Use Erase-RAM to check location if free before write"
set_parameter_property OCCUPANCY_CHECK DEFAULT_VALUE true
set_parameter_property OCCUPANCY_CHECK DISPLAY_NAME OCCUPANCY_CHECK
set_parameter_property OCCUPANCY_CHECK TYPE BOOLEAN
set_parameter_property OCCUPANCY_CHECK ENABLED false
set_parameter_property OCCUPANCY_CHECK UNITS None
set_parameter_property OCCUPANCY_CHECK DESCRIPTION "Use Erase-RAM to check location if free before write"
set_parameter_property OCCUPANCY_CHECK HDL_PARAMETER true
add_parameter ENCODE_ADDRESS_OUT BOOLEAN true "Encode the output address from one-hot to binary"
set_parameter_property ENCODE_ADDRESS_OUT DEFAULT_VALUE true
set_parameter_property ENCODE_ADDRESS_OUT DISPLAY_NAME ENCODE_ADDRESS_OUT
set_parameter_property ENCODE_ADDRESS_OUT TYPE BOOLEAN
set_parameter_property ENCODE_ADDRESS_OUT ENABLED false
set_parameter_property ENCODE_ADDRESS_OUT UNITS None
set_parameter_property ENCODE_ADDRESS_OUT DESCRIPTION "Encode the output address from one-hot to binary"
set_parameter_property ENCODE_ADDRESS_OUT HDL_PARAMETER true


# 
# display items
# 
add_display_item "" Basic GROUP ""
add_display_item "" Advanced GROUP ""
add_display_item "" Optional GROUP ""
add_display_item "" Basics GROUP ""


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock i_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink i_rst reset Input 1


# 
# connection point cam_i_cmp_din
# 
add_interface cam_i_cmp_din conduit end
set_interface_property cam_i_cmp_din associatedClock clock
set_interface_property cam_i_cmp_din associatedReset ""
set_interface_property cam_i_cmp_din ENABLED true
set_interface_property cam_i_cmp_din EXPORT_OF ""
set_interface_property cam_i_cmp_din PORT_NAME_MAP ""
set_interface_property cam_i_cmp_din CMSIS_SVD_VARIABLES ""
set_interface_property cam_i_cmp_din SVD_ADDRESS_GROUP ""

add_interface_port cam_i_cmp_din i_cmp_din std_logic_vector Input 80


# 
# connection point cam_i_wr_addr
# 
add_interface cam_i_wr_addr conduit end
set_interface_property cam_i_wr_addr associatedClock clock
set_interface_property cam_i_wr_addr associatedReset ""
set_interface_property cam_i_wr_addr ENABLED true
set_interface_property cam_i_wr_addr EXPORT_OF ""
set_interface_property cam_i_wr_addr PORT_NAME_MAP ""
set_interface_property cam_i_wr_addr CMSIS_SVD_VARIABLES ""
set_interface_property cam_i_wr_addr SVD_ADDRESS_GROUP ""

add_interface_port cam_i_wr_addr i_wr_addr std_logic_vector Input 16


# 
# connection point cam_i_wr_data
# 
add_interface cam_i_wr_data conduit end
set_interface_property cam_i_wr_data associatedClock clock
set_interface_property cam_i_wr_data associatedReset ""
set_interface_property cam_i_wr_data ENABLED true
set_interface_property cam_i_wr_data EXPORT_OF ""
set_interface_property cam_i_wr_data PORT_NAME_MAP ""
set_interface_property cam_i_wr_data CMSIS_SVD_VARIABLES ""
set_interface_property cam_i_wr_data SVD_ADDRESS_GROUP ""

add_interface_port cam_i_wr_data i_wr_data std_logic_vector Input 80


# 
# connection point cam_i_wr_en
# 
add_interface cam_i_wr_en conduit end
set_interface_property cam_i_wr_en associatedClock clock
set_interface_property cam_i_wr_en associatedReset ""
set_interface_property cam_i_wr_en ENABLED true
set_interface_property cam_i_wr_en EXPORT_OF ""
set_interface_property cam_i_wr_en PORT_NAME_MAP ""
set_interface_property cam_i_wr_en CMSIS_SVD_VARIABLES ""
set_interface_property cam_i_wr_en SVD_ADDRESS_GROUP ""

add_interface_port cam_i_wr_en i_wr_en std_logic Input 1


# 
# connection point cam_o_match_addr
# 
add_interface cam_o_match_addr conduit end
set_interface_property cam_o_match_addr associatedClock clock
set_interface_property cam_o_match_addr associatedReset reset_sink
set_interface_property cam_o_match_addr ENABLED true
set_interface_property cam_o_match_addr EXPORT_OF ""
set_interface_property cam_o_match_addr PORT_NAME_MAP ""
set_interface_property cam_o_match_addr CMSIS_SVD_VARIABLES ""
set_interface_property cam_o_match_addr SVD_ADDRESS_GROUP ""

add_interface_port cam_o_match_addr o_match_addr std_logic_vector Output 16


# 
# connection point cam_o_match_flag
# 
add_interface cam_o_match_flag conduit end
set_interface_property cam_o_match_flag associatedClock clock
set_interface_property cam_o_match_flag associatedReset reset_sink
set_interface_property cam_o_match_flag ENABLED true
set_interface_property cam_o_match_flag EXPORT_OF ""
set_interface_property cam_o_match_flag PORT_NAME_MAP ""
set_interface_property cam_o_match_flag CMSIS_SVD_VARIABLES ""
set_interface_property cam_o_match_flag SVD_ADDRESS_GROUP ""

add_interface_port cam_o_match_flag o_match_flag std_logic Output 1


# 
# connection point cam_o_match_count
# 
add_interface cam_o_match_count conduit end
set_interface_property cam_o_match_count associatedClock clock
set_interface_property cam_o_match_count associatedReset ""
set_interface_property cam_o_match_count ENABLED true
set_interface_property cam_o_match_count EXPORT_OF ""
set_interface_property cam_o_match_count PORT_NAME_MAP ""
set_interface_property cam_o_match_count CMSIS_SVD_VARIABLES ""
set_interface_property cam_o_match_count SVD_ADDRESS_GROUP ""

add_interface_port cam_o_match_count o_match_count std_logic_vector Output 16


# 
# connection point cam_o_wr_rd
# 
add_interface cam_o_wr_rd conduit end
set_interface_property cam_o_wr_rd associatedClock clock
set_interface_property cam_o_wr_rd associatedReset ""
set_interface_property cam_o_wr_rd ENABLED true
set_interface_property cam_o_wr_rd EXPORT_OF ""
set_interface_property cam_o_wr_rd PORT_NAME_MAP ""
set_interface_property cam_o_wr_rd CMSIS_SVD_VARIABLES ""
set_interface_property cam_o_wr_rd SVD_ADDRESS_GROUP ""

add_interface_port cam_o_wr_rd o_wr_rd writeresponsevalid_n Output 1


# 
# connection point cam_i_init_en
# 
add_interface cam_i_init_en conduit end
set_interface_property cam_i_init_en associatedClock clock
set_interface_property cam_i_init_en associatedReset ""
set_interface_property cam_i_init_en ENABLED true
set_interface_property cam_i_init_en EXPORT_OF ""
set_interface_property cam_i_init_en PORT_NAME_MAP ""
set_interface_property cam_i_init_en CMSIS_SVD_VARIABLES ""
set_interface_property cam_i_init_en SVD_ADDRESS_GROUP ""

add_interface_port cam_i_init_en i_init_en std_logic Input 1

